# Establish a tunnel to our public IP endpoint
---

- name: Create tunnel group
  group:
    name: "{{ tunnel_group }}"

- name: Create tunnel user
  user:
    name: "{{ tunnel_user }}"
    group: "{{ tunnel_group }}"
    home: "{{ tunnel_user_home }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096

- name: Install autossh
  apt:
    name: autossh
    state: present

- name: Add systemd unit file for autossh
  template:
    src: autossh.service
    dest: /etc/systemd/system/autossh.service
    owner: root
    group: root
    mode: 0755

- name: Run autossh service
  service:
    name: autossh
    state: started
    enabled: yes