---
- hosts: freshraspberrypi
  vars_prompt:
    - name: "pi_hostname"
      prompt: "New pi hostname"
      private: no
    - name: "pi_password"
      prompt: "New pi password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
  tasks:
  - name: Set host name in /etc/hostname
    become: yes
    hostname:
      name: "{{ pi_hostname }}"
  - name: Set host name in /etc/hosts
    become: yes
    lineinfile:
      dest: /etc/hosts
      regexp: "^127.0.1.1"
      line: "127.0.1.1\t{{ pi_hostname }}"
      state: present
  - name: Disable DNS lookup on SSH login to avoid delays
    become: yes
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "UseDNS"
      line: "UseDNS no"
      state: present
  - name: Set authorized key for user ubuntu copying it from current user
    authorized_key:
      user: "pi"
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  - name: Set a new password pi user
    become: yes
    user:
      name: "pi"
      password: "{{ pi_password }}"