# Install and configure Gogs
---

- name: Create Gogs group
  group:
    name: "{{ gogs_group }}"

- name: Create Gogs user
  user:
    name: "{{ gogs_user }}"
    group: "{{ gogs_group }}"
    home: "{{ gogs_user_home }}"

- name: Mount data storage on memory stick 
  mount:
    path: /data
    src: LABEL=DATA
    fstype: auto
    opts: nofail,uid=git,gid=git,umask=0022,sync,auto,nosuid,rw,nouser
    state: present
 
- name: Ensure git is installed
  apt:
    name: git
    state: present

- name: Download and install Gogs
  unarchive:
    remote_src: yes
    src: "{{ gogs_binary_url }}"
    creates: "{{ gogs_install_dir }}"
    dest:  "{{ gogs_install_dir | dirname }}"
    group: root
    owner: root

- name: Create Gogs config dir
  file: 
    path: "{{ gogs_user_home }}/gogs"
    state: directory
    recurse: yes

- name: Write Gogs configuration
  template:
    src: app.ini
    dest: "{{ gogs_user_home }}/gogs/app.ini"

- name: Add systemd unit file for Gogs
  template:
    src: gogs.service
    dest: /etc/systemd/system/gogs.service
    owner: root
    group: root
    mode: 0755

- name: Run Gogs service
  service:
    name: gogs
    state: started
    enabled: yes
