# Install and configure Gogs
---

- name: Mount data storage on memory stick 
  mount:
    path: /data
    src: LABEL=DATA
    fstype: auto
    opts: nofail,uid=pi,gid=pi,umask=0022,sync,auto,nosuid,rw,nouser
    state: present
 
- name: Ensure git is installed
  apt:
    name: git
    state: present
